"""rename address

Revision ID: 41470ef91386
Revises: 8e033204ed56
Create Date: 2024-07-02 13:29:37.721977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41470ef91386'
down_revision = '8e033204ed56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###